name: Test-Build

 on: 
  push:
   branches: 
     - main
jobs:
  test-api:
    runs-on: ubuntu-latest
       steps:
      - uses: actions/checkout@v2
        
        #Install NODE on the runner
        
- name: Install Node
  uses: actions/setup-node@v1
  with:
    node-version: "12.x"
  
  
        #Install Newman command line and HTML Extra Report
        
- name: Install newman
  run: |
  npm install -g newman
  npm install -g newman-reporter-htmlextra

        #Make directory to upload test results
  
- name: Make Directory for results
  run: mkdir -p testResults

        #Run the POSTMAN Collection
        
- name: Run POSTMAN Collection
  run: |
    newman run mycollection.postman_collection.json -e workspace.postman_globals.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  >  testResults/runreport1.html
    
          #Upload de test Results to workspace
          
  - name: Output the run Details
    uses: actions/upload-artifact@v2
    with:
      name: RunReports
      path: testResults
